### PR TITLE
Sale base

### PR DESCRIPTION
**Pull request by Outblaze**
This is used for our sale contract.
Not sure about these changes for the imports, I couldn't have it work without that.
Maybe you have a solution @wighawag ?

### CODE REVIEW

**Comment by wighawag** [comment]
That's weird and this will break our setup as our contracts are in "src" not "contracts" folder
Is this a truffle issue ?

As for pragma = 0.5.12 this will also break our setup as we use an earlier version of solidity.

I think common library should use a lower end version only so each project can decide which solidity version they want to use.

**Comment by ghost** [comment]
It's probably a Truffle thing since we are using it.
Fixed the pragmas. What version of solidity are you using? Solidified recommended to use 0.5.12.

**Comment by wighawag** [comment]
We use 0.5.9 and our contract has been audited with that in mind.
For later contract, we will consider updating to the latest version

**Comment by wighawag** [comment]
Did you manage to solve the issue on truffle side ?

**Comment by ghost** [comment]
What about setting your minimum at 0.5.9 instead of 0.5.2 then?
Didn't look into the truffle import thing, we're gonna look into it

**Comment by wighawag** [comment]
This is just because before we were building on earlier solidity version and 0.5.2 was the one we were using.
We could update if we want but unless solidity changes its syntax, it has no effect to increase the minimum version, the version used to compile will be the one you pick when compiling.
I really don't mind though.

**Comment by ghost** [comment]
The code should be good to merge now, except if you have other comments. Thanks @wighawag

**Pull request merged**
